### ISSUE TITLE
Meta Schema as external file

### ISSUE THREAD

**Issue by pmk65** [DeepBlueCLtd/json-schema-editor#9]
Have you considered putting the meta schema into a separate file and add a "loadFile" function to get it?
That would allow users to easily change the meta schema to another.
If you need it, you can extract the load function from my Playground code.

**Comment by IanMayo** [comment]
Thanks for the suggestion @pmk65 .

I mis-interpreted when I first read it.  I thought you were suggesting a "load-file" for the schema that's being edited.  That would allow "round-tripping", to an extent:
* load a schema
* edit the schema
* preview the schema
* save the new schema [1]

You've suggested being able to switch to a new meta-schema.  In this project we're trying to develop a specific JSON Meta-Schema that suits editing JSON-Schemas to be used in the JSON-Editor.  So, it may remove some fields/attributes that aren't present, and include other fields that are.

The meta-schema is editable in the current working draft so that we can dynamically experiment with the content of the custom meta-schema.  But, once we're happy with the meta-schema, our intention is that it will no longer be editable (or even visible).

Did you have some other usage in mind?


[1]. No, using the current technologies we aren't able to save the schema back to where it came from - so it will have to be done by the user.

**Comment by pmk65** [comment]
I was thinking of the meta schema, not the generated schema, as I read that you was reducing the available types in the selectbox.
But a more advanced user might want to have all types available. So switching between meta schemas could be a useful feature.

[1] Saving the generated schema as a JSON file is pretty easy. I just posted a `SaveAsFile` function at the JSON-Editor github. https://github.com/json-editor/json-editor/issues/307#issuecomment-467058314

**Comment by IanMayo** [comment]
Aah, I see.  Yes, that's a valid suggestion.

Oh, and I guess that if the user is able to "Save as" over the existing schema then it would have full round-trip support

Thanks for your input, @pmk65

**Comment by pmk65** [comment]
Another idea/suggestion: Supposed I got a JSON result array, then it would be nice if I could upload/paste it in somewhere as a default/starting value.
And then get the MetaEditor to update based on the values from the result array. That way I don't have to add properties first and select type, but build on an existing result array.

**Comment by IanMayo** [comment]
Hello there @pmk65 , thanks for the new suggestion.

I've got a couple of queries:
1. Do you mean a JSON array, or a JSON document?
2. Do you mean to reverse engineer the schema (& thus schema editor) from the document, to create an initial version of the schema?

But, if I'm still off-track, would you mind providing an example of what you're imagining?

(I'm keen that we understand the diverse set of potential requirements)

**Comment by pmk65** [comment]
1) JSON Array or document, it doesn't matter. Just as long as the content is a JSON array/object.
2) Yes. The [demo.html](https://rawgit.com/json-editor/json-editor/master/docs/demo.html) at JSON-Editor does something like that if you in the schema field add an empty object 
````json
{}
````
And then in the "JSON Output" paste in something like this and press the "Update Form" button.
````json
{
  "name": "Jeremy Dorn",
  "age": 25,
  "favorite_color": "#ffa500",
  "gender": "male",
  "date": "",
  "location": {},
  "pets": [
    {
      "type": "dog",
      "name": "Walter"
    }
  ]
}
````
Then you'll see that it populates the "Editor" form and create default field types based on the content types. But the "Schema" output unfortunately doesn't change.

**Comment by IanMayo** [comment]
Ok.  In the JSON-Editor context, "Update Form" populates the editor with the JSON document.

So, in this JSON-Schema-Editor context, it's a JSON Schema document that would be pasted into the "Output" text-area, and then the editor gets updated with that schema.

What you're describing is a logical step further.  You're describing a JSON document being pasted into a new text-area, then an algorithm parses the document to derive a JSON schema, then paste that content into the `Output` window, then re-populate the editor with the content of that schema.

I recognise the value in that process, but deriving the schema from the document is a step that's not currently perform in JSON-Editor (note - I think I've found JS code to do it here [1]).

It's a _stretch target_, but it's a great target to aim for :-)

Thanks @pmk65 

https://github.com/easy-json-schema/easy-json-schema

**Comment by IanMayo** [comment]
Ok, we're going to close this issue.

If a user is trialling use of the Schema Editor with different versions of the Meta-Schema, I'm choosing to interpret this as a developer role, and that the developer should make a code modification to include the alternate meta-schema.

I'm going to transfer the "derive schema from document" to another issue.
